### ISSUE TITLE
mean method for labelled vector

### ISSUE THREAD

**Issue by larmarange** [sjPlot/sjmisc#13]
Hello,

I was doing few tests around the **labelled** package and I discovered few things.

I created the following object:

```r
notes <- c(12, 16, 99, 14, 17)
val_label(notes, 99) <- "absent le jour de l'examen"
missing_val(notes) <- 99
```

I was expecting to observe:

```
> mean(notes)
[1] 31.6
> mean(missing_to_na(notes), na.rm = TRUE)
[1] 14.75
```

Surprisingly, in some cases, I was  obtaining:

```
> mean(notes)
[1] 14.75
```

I tried to explore the reason of that and it appears by using `getS3method` that the `mean` method defined in **sjmisc** was called by **R** (even if I didn't attached **sjmisc**). I don't know why in some cases **R** was retrieving this method and in other cases he was not, but it raises at least few comments about having a `mean` method defined for `labelled` vectors:

- first of all, `mean` method will return different values according to the package currently loaded in memory. And it's something completely invisible for most users;
- I get a result while I didn't specify `na.rm = TRUE` and so it's so consistent with the original method;
- almost of statistical functions in **R** are not taking into account the `labelled` class. Nevertheless, the advantage of the labelled class is that it preserves original values and that these vectors can be used with any statistical function in **R**, while the approach used by **memisc** with `data.set` objects is working with a limited number of compatible functions;
- therefore when dealing with labelled data, the first thing that a user need to be aware is that it his responsibility to say explicitly what he want to do with self-defined missing values: (i) keeping them (and then considering there are valid values) or converting them to `NA` with `missing_to_na`. 
- According to the performed analysis, both approaches could be appropriate. In order to be consistent with the vast majority of **R** functions, my position is that self-defined missing values should always be converted to NA only if explicitly requested by the user using `missing_to_na` function. In that scenario, we ensure that the way to use the data is always the same, without having to remember which functions  are taking into account labels attributes.

Therefore, I'm not sure that it would be appropriate to provide a `mean` method for `labelled` class. If we provide such method, at least we should get the same results than without that method for consistency. However, an option could be to display a warning message to alert the user that there are currently self-defined missing values.  For example: providing a `missing_to_na` argument with default value equal to `NULL`:
- if `NULL`, results will be the same that the default mean method, but a Warning will be displayed in case some missing values are defined.
- if `FALSE`, self-defined missing values are not converted but no warning displayed;
- if `TRUE`, self-defined missing values are converted to NA before computing the mean, the user having always to specify the value of `na.rm`

What do you think?

**Comment by sjPlot** [comment]
Yes, that sounds good! I was not completely satisfied with overriding the default parameters for `mean.labelled`.

**Comment by larmarange** [comment]
But I'm not sure if such method should be provided by **labelled** package or if it should remain in **sjmisc**.

**Comment by sjPlot** [comment]
If both methods do the same thing, why not having them in both packages (as probably people only use one of the two packages for labelled data)? As far as I know, `Hmisc` also has a print-method for labelled data, which, however, "breaks" the print method of `haven`. Are there good reasons to have the generic methods in only one package?

**Comment by sjPlot** [comment]
Close this for now - probably, I'll get back to this issue when the _labelled_ package is released and we'll be more clear which would be a feasible way of implementing the mean-method.
