### ISSUE TITLE
set_na() results in 0 instead of NA

### ISSUE THREAD

**Issue by frankcsliu** [sjPlot/sjmisc#15]
> load(tscs2013)
> str(tscs2013$v66)
 Factor w/ 8 levels "1","2","3","4",..: 3 2 1 4 2 3 1 3 2 2 ...
 - attr(*, "value.labels")= Named chr [1:10] "99" "98" "97" "96" ...
  ..- attr(*, "names")= chr [1:10] "遺漏值" "拒答" "不知道" "跳答" ...
 - attr(*, "label")= Named chr "66 如果台灣宣布獨立,請問您認為兩岸會不會發生戰爭? "
  ..- attr(*, "names")= chr "v66"

>  tscs2013 <- set_na(tscs2013, 94:98)  
> str(tscs2013$v66)
 Factor w/ 8 levels "1","2","3","4",..: 3 2 1 4 2 3 1 3 2 2 ...
 - attr(*, "value.labels")= Named chr [1:5] "99" "4" "3" "2" ...
  ..- attr(*, "names")= chr [1:5] "遺漏值" "一定不會" "可能不會" "可能會" ...
 - attr(*, "label")= Named chr "66 如果台灣宣布獨立,請問您認為兩岸會不會發生戰爭? "
  ..- attr(*, "names")= chr "v66"

> table(tscs2013$v66)
  1    2      3      4   94  95  97  98 
425 736 464 179    0    0    0    0 

I was expecting that the level of variables like v66 goes down to 4 and that 94 to 98 become NA. Did I miss anything? Thank you. 
ps. 
The data used for this practice is downloadable from here: http://cl.ly/0I332p1i2Q3H/tscs2013.rda

**Comment by sjPlot** [comment]
I can't reproduce the example, because `v66` has no value 94 to 98.

    > library(sjmisc)
    > load("~/Desktop/tscs2013.rda")
    > str(tscs2013$v66)
     atomic [1:1952] 3 2 1 4 2 3 1 3 2 2 ...
     - attr(*, "value.labels")= Named chr [1:4] "4" "3" "2" "1"
      ..- attr(*, "names")= chr [1:4] "一定不會" "可能不會" "可能會" "一定會"
     - attr(*, "label")= Named chr "66 如果台灣宣布獨立,請問您認為兩岸會不會發生戰爭? "
      ..- attr(*, "names")= chr "v66"

    > table(tscs2013$v66)

      1   2   3   4 
    425 736 464 179 

    > tscs2013 <- set_na(tscs2013, 94:98)
    > table(tscs2013$v66)

      1   2   3   4 
    425 736 464 179

**Comment by frankcsliu** [comment]
Sorry for my belated response. Attached please find the raw data, saved directly from the original sav file. 
http://cl.ly/1n2K1b0l1Y1O/tscs2013_raw.rda

Thank you.
