### ISSUE TITLE
add_labels error

### ISSUE THREAD

**Issue by jerryzhujian9** [sjPlot/sjmisc#16]
I was trying the example code and got an error:

efc.sub <- subset(efc, subset = e16sex == 1, select = c(4:8))
efc.sub <- add_labels(efc.sub, efc)

--->
Error in order(as.numeric(all.labels)) : 
  (list) object cannot be coerced to type 'double'

Can you take a look?

**Comment by sjPlot** [comment]
I guess this is due to a change in function names. See `?add_labels`, which now works differently. The former `add_labels` was renamed to `copy_labels`.

**Comment by jerryzhujian9** [comment]
Thanks for your quick response! Indeed that was the case. with copy_labels, it works fine. Sorry for being panic earlier. A new useR here, thanks for your great package for making SPSS users have an easy transition!
