### ISSUE TITLE
t-values?

### ISSUE THREAD

**Issue by zeltak** [sjPlot/sjmisc#17]
Hi!

thx so much for this wonderful package! i really enjoy using it.

One thing that i cant seem to find is how to add t-values to the table? is it possible?

thx!

Z

**Comment by sjPlot** [comment]
t-values to which table? To which function are you referring?

**Comment by zeltak** [comment]
Hi sorry, to a sjt.lm output. i need to add the t-values to the table. is that possible?

thx so much on advance

Z

**Comment by sjPlot** [comment]
Ok, so this affects the `sjPlot` package, not `sjmisc`. I opened an issue there:

https://github.com/sjPlot/devel/issues/98

**Comment by sjPlot** [comment]
Currently it's not possible to show t-values. Maybe I'll implement this option in a future update.

**Comment by svannoy** [comment]
I hope so!
