### ISSUE TITLE
Erroneous assignment of value labels to subset data when using copy_labels 

### ISSUE THREAD

**Issue by LechAttack** [sjPlot/sjmisc#20]
An issue concerning the usage of ` copy_labels`:

When subsetting data using subset{base}, haven-style variable and value labels are lost.
To restore labels, sjmisc offers the `copy_labels ` function.
However, this function may fail to reproduce the collect labels in the following scenario: (a) if the subset dataframe is a subset of variables (columns) AND cases (rows);  and (b) if, consequently, some of the original variable values are no longer contained in the subset dataset. 
In this case, ` copy_labels ` uses the first variable labels.
> More labels than values of "var1". Using first 3 labels.

This can lead to wrong assignments of value labels, however. In my specific case, value labels of missing values from the original dataframe were erroneously assigned to non-missing values in the subset dataframe.

Is there any way to make sure that the correct original value labels are reassigned?

I think for such instances, `copy_labels` could benefit from having a similar argument to that of "force.labels = TRUE" in `set_labels`? 

Note: This issue only appears to occur when using the haven-style but not when requesting foreign-style labels in sjmisc's the ` read_spss ` command. Might this have to do with the way in which missing variables are treated per default in haven vs. foreign?

Thanks!

**Comment by sjPlot** [comment]
Working example:

```
data(efc)
efc.sub <- subset(efc, subset = e16sex == 1 & c172code == 3, select = c(4:8))
str(efc.sub)

efc.sub <- copy_labels(efc.sub, efc)
str(efc.sub)
```

`efc.sub$c82cop1` was not correctly assigned previously, but now is.
