### ISSUE TITLE
`merge_df()` unexpected behaviour

### ISSUE THREAD

**Issue by dchiu911** [sjPlot/sjmisc#24]
I have a list of `data.frames` each with `labelled` and/or `labelled_spss` variables that I want to merge. Unfortunately, `plyr::join_all()` removes the `"label"`, `"na_values"`, and `"format.spss"` attributes.

I was hoping that `merge_df()` would be able to retain these attributes, but I got the following error message:

```{r}
Error in `[[<-.data.frame`(`*tmp*`, i, value = c(NA, NA, NA, NA, NA, NA,  : 
  replacement has 4821 rows, data has 9441
```
If this issue is more `haven`-esque I'll make an issue there, thanks!

**Comment by dchiu911** [comment]
In essence, what I wanted to achieve was a wrapper for `merge(x1, x2, all = TRUE)`
but it seems like `merge_df()` is doing something a little different:

```{r}
x1 <- efc %>% dplyr::select(1:5) %>% slice(1:10)
x2 <- efc %>% dplyr::select(3:7) %>% slice(1:10)
merge(x1, x2, all = TRUE) %>% dim()
# [1] 10  7
merge_df(x1, x2) %>% dim()
# [1] 20  7
```

**Comment by sjPlot** [comment]
Ok, this was a wrong description in the docs of `merge_df()`. I think I had an example where base `merge()` did the same as `merge_df()`, but maybe I was wrong or using a very specific example, which yielded the same results in both `merge()` and `merge_df()`.

`merge_df()` intends to "append" two data frames, thus it is an additional feature to dplyr's `join_*()` functions. So, it's working as intended, just the description with merge() was wrong. I fixed the docs.

**Comment by sjPlot** [comment]
btw, dplyr's join-function preserve all label attributes, so you can use these if you need other join-operations.

**Comment by dchiu911** [comment]
Thanks for the clarifications! Yes I used `dplyr::left_join()` to much avail.

**Comment by sjPlot** [comment]
A typical use case is for example, if you have different country data sets that share a common amount of variables, plus some country specific variables for each country. You can then "merge" these data sets, i.e. all are "row bound", while the specific variables that only appear in one of the data sets is also added as new column, with NA values for those subsets that don't have this variable.
