### ISSUE TITLE
Suggestion: search function for variable labels

### ISSUE THREAD

**Issue by methodds** [sjPlot/sjmisc#27]
Hi,

I have a suggestion for a utility function to search for all variables containing a specific string within their variable labels. I'm sure you would come up with a better version and without the ``dplyr`` dependency:

```
lookfor <- function(x, df) {
  cols <- colnames(df)
  labels <- get_label(df)
  combined <- data.frame(cols, labels) %>% 
  filter(grepl(tolower(x), tolower(labels)))
  return(combined)
}

> lookfor('elder', efc)
      name                 label
1 e15relat relationship to elder
2   e16sex        elder's gender
3   e17age            elder' age
4   e42dep    elder's dependency
5 tot_sc_e  Services for elderly
```

**Comment by sjPlot** [comment]
Is already implemented, just a few days ago:

https://github.com/sjPlot/sjmisc/blob/master/R/find_var.R

Update also already submitted to CRAN.

**Comment by methodds** [comment]
Awesome, thank you :)
