### ISSUE TITLE
describe for single variables or vectors

### ISSUE THREAD

**Issue by methodds** [sjPlot/sjmisc#28]
Hi, I just found your  wrapper ``sjt.df`` which produces a nice summary of descriptive statistics. Is it possible to have this for one or several variables and without the html formatting? I'm basically looking for the equivalent of ``frq`` for the summary statistics.

Of course, one could do something like ``sjt.df(efc[['e17age'])``, but this has no console output and it would be convenient if one would not have to extract the variable(s) out of a dataset first.

**Comment by sjPlot** [comment]
Do you mean `psych::describe`?

**Comment by methodds** [comment]
yes like a miniwrapper around it, with optional support for displaying variable name and variable label.
