### ISSUE TITLE
unable to process set_na()

### ISSUE THREAD

**Issue by frankcsliu** [sjPlot/sjmisc#29]
I got this message when I use this function: 

> tscs2013r <- set_na(tscs2013r, c(92:99, "NA"))  
Error in as.Date.numeric(value) : 'origin' must be supplied

It worked this summer but somehow this won't work this time when I came back to this project. Did I miss anything? Thank you.

**Comment by sjPlot** [comment]
Maybe it has to do with the support of tagged NA values? Try using argument `as.tag = FALSE`.

**Comment by frankcsliu** [comment]
Thank you. It solved the problem. Tagged missing values are for SAS and Stata users, as the haven package says, so how about setting as.tag default value to FALSE? I and my students would love to type less.

**Comment by sjPlot** [comment]
Tagged NA values can be used in R in the same way as regular NA, so you can enhance the capabilities of labelled data to NA values in R as well. It's just that labelled missing values in data files from packages like SAS, Stata or SPSS are imported as tagged NA into R. So, it's not just related to SAS, Stata or SPSS users - you can use tagged NA in R without any relationship to the other packages. 

But maybe I can change the defaults from argument `as.tag`, or find a fix for Date values. Do you have a small minimal reproducible example? It looks like a Date variable is causing troubles.

**Comment by frankcsliu** [comment]
Please use this data set
http://jmp.sh/pJGXkxa

tscs2013r <- set_na(tscs2013q2, c(92:99, "NA"), as.tag = F) 
I had the error message without specifying as.tag=F. 
Thank you!
