### ISSUE TITLE
Labels disappear with too many variables in sjp.glm?

### ISSUE THREAD

**Issue by ode45** [sjPlot/sjmisc#30]
Thanks for the great work Daniel! Today I encountered a minor issue. When I make a plot with many variables my labels disappear. Is there a way or argument to avoid this?

y <- sample(0:1, 200, replace = TRUE)
a <- as.factor(sample(1:4, 200, replace = TRUE))
b <- as.factor(sample(1:4, 200, replace = TRUE))
c <- sample(1:4, 200, replace = TRUE)

set_label(y) <- "var y"
set_label(a) <- "var a"
set_label(b) <- "var b"
set_label(c) <- "var c"

#OK: shows the labels of the variables
fit1 <- glm(y~a+c, family = binomial(link = "logit"))
sjp.glm(fit1)

![ok](https://cloud.githubusercontent.com/assets/8698082/20947780/caa06ec6-bbde-11e6-8539-4cb9e06fd01b.png)

#NOT OK: shows the variable names instead of the labels
fit2 <- glm(y~a+b, family = binomial(link = "logit"))
sjp.glm(fit2)

![wrong](https://cloud.githubusercontent.com/assets/8698082/20947784/cdbe50e6-bbde-11e6-9917-89ebec3c4aef.png)

**Comment by sjPlot** [comment]
This is an issue of the sjPlot-package, should be fixed now.

**Comment by ode45** [comment]
Great, it's indeed working wonderful now. Danke schön!
