### ISSUE TITLE
Suggestion:: xtab function similar to frq()

### ISSUE THREAD

**Issue by methodds** [sjPlot/sjmisc#31]
Hi, it would be pretty nice to have a simple function ```xtab``` that, like ```frq()``` related to ```sjt.frq()```, generates a simple non-html contingency table including value labels.

Related to this, it would also be useful to either have a parameter for this function and ```frq()```, which would  also print the variable label above the table, or just print the variable as default.

**Comment by sjPlot** [comment]
For the first issue, see `sjmisc::flat_table()`.

**Comment by methodds** [comment]
Thanks, but I already tried that earlier without success. Could it be that ```flat_table()``` **only** shows values for which there exists a label and omits all other values from the output?

**Comment by sjPlot** [comment]
Yes, you're right. You have to wrap the data frame in `fill_labels()`:

```
x <- sample(1:4, 20, T)
y <- sample(1:4, 20, T)
set_labels(x) <- c(`first` = 1, `third` = 3, `fourth` = 4)
set_labels(y) <- c(`second` = 2, `fourth` = 4)
tib <- tibble::tibble(x, y)
flat_table(fill_labels(tib), x, y)
```

else, use `to_label()`:

```
tib <- to_label(tib, add.non.labelled = T)
ftable(tib$x, tib$y)
```

**Comment by sjPlot** [comment]
I think it doesn't make sense to exclude non-labelled values, so I fixed this.

**Comment by methodds** [comment]
Thank you for the update! What do you think about  showing variable labels for ``frq()`` and ``fill_table()``? In my opinion this would make them basically "swiss army knives" so that one can have a brief look at all important information about variables with one single (non-html) command. If you want I can also open another issue for this.

By the way: I am just in the process of converting a Data Analysis course for Social Scientists from Stata to R and thanks to your package this works out incredibly well! :)

**Comment by sjPlot** [comment]
For `frq()`, variable labels are already shown (in the current GitHub-build). For `flat_table()`, I have no good idea where to show the labels, because you can have a table with 2, 3, 4 or more variables. And the object itself is an `ftable()`, so I can't easily format the console-output.

> By the way: I am just in the process of converting a Data Analysis course for Social Scientists from Stata to R and thanks to your package this works out incredibly well! :)

Glad to here that, and thanks for the feedbacks you provide - this helps me improving the package not only for other users, but also for my purposes.

**Comment by methodds** [comment]
I see, thanks for the ``frq()`` update. There is one more thing I would like to suggest: I think  ``frq()`` should either not display value labels for which no observations are occurent at all, or have a parameter which would enable this behavior. The background is the following: In several datasets I work with there are  much more value labels assigned than actually observed later on. Using ``frq()`` on such variables spams the screen with a lot of unnecessary information. I am not sure whether this change is relevant for SPSS datasets, but it definitely is for Stata.

**Comment by sjPlot** [comment]
As a First workaround you could wrap the variable in `drop_labels()`.
