### ISSUE TITLE
rec()  problems with val.labels and suggestion

### ISSUE THREAD

**Issue by methodds** [sjPlot/sjmisc#32]
Hi, 

I have a very strange problem with ``rec()``: When I use ``efc`` data to recode an age variable, ``val.labels`` works without any issues:

````
data(efc)
 
> alt_kat <-  rec(efc$e17age, "18:23=1; 24:65=2; 66:max=3",
+    var.label="Alter kat.", 
+    val.labels= c("18-23"=1,"24-65"=2,"ueber65"=3))
> frq(alt_kat)
# Alter kat.

 val   label frq raw.prc valid.prc cum.prc
   1   18-23   0    0.00       0.0     0.0
   2   24-65  32    3.52       3.6     3.6
   3 ueber65 858   94.49      96.4   100.0
   4      NA  18    1.98        NA      NA
````
However, when I use the exact same syntax for a Stata dataset the following happens:

````
d$alter <- 2013 -  set_na(d$q2c,-99:-97)
 d$alt_kat <-  rec(d$alter, "18:23=1; 24:65=2; 66:max=3",
+    var.label="Alter kat.", 
+    val.labels= c("18-23"=1,"24-65"=2,"ueber65"=3))
> frq(d$alt_kat)
# Alter kat.

 val label  frq raw.prc valid.prc cum.prc
   1     1   77    3.85      3.90    3.90
   2     2 1174   58.67     59.47   63.37
   3     3  723   36.13     36.63  100.00
   4    NA   27    1.35        NA      NA
````
The value labels were not passed over. The only way to change this is by not explicitly specifying the numericals for value labels:

````
alt_kat <-  rec(d$alter, "18:23=1; 24:65=2; 66:max=3",
+    var.label="Alter kat.", 
+    val.labels= c("18-23","24-65","ueber65"))
> frq(alt_kat)
# Alter kat.

 val   label  frq raw.prc valid.prc cum.prc
   1   18-23   77    3.85      3.90    3.90
   2   24-65 1174   58.67     59.47   63.37
   3 ueber65  723   36.13     36.63  100.00
   4      NA   27    1.35        NA      NA
````
Do you know why this happens? I would be happy to just skip the numericals, but from what I understand the order is not based upon the order of  recodings, but based upon which values appear first in a vector. At least this seems to be true for another example:

````
frq(d$q1)
# Geschlecht
 val                label  frq raw.prc valid.prc cum.prc
 -99    -99. keine Angabe    0    0.00      0.00    0.00
 -98     -98. weiss nicht    0    0.00      0.00    0.00
 -97 -97. trifft nicht zu    0    0.00      0.00    0.00
   1         1. maennlich 1013   50.62     50.62   50.62
   2          2. weiblich  988   49.38     49.38  100.00
   3                   NA    0    0.00        NA      NA

> d$sex <- rec(d$q1, "2=1;1=0;else=NA", 
+              var.label="sex", val.labels=c('Frau'=1, 'Mann'=0))
> d$sex2 <- rec(d$q1, "2=1;1=0;else=NA", 
+              var.label="sex", val.labels=c('Frau', 'Mann'))

> frq(d$sex)
# sex
val label  frq raw.prc valid.prc cum.prc
   0  Frau  988   49.38     49.38   49.38
   1  Mann 1013   50.62     50.62  100.00
   2    NA    0    0.00        NA      NA

> frq(d$sex2)
# sex
 val label  frq raw.prc valid.prc cum.prc
   0  Frau 1013   50.62     50.62   50.62
   1  Mann  988   49.38     49.38  100.00
   2    NA    0    0.00        NA      NA
````

The complete dataset I used for the output (and for most other examples I provide in issues) is available [here](https://www.dropbox.com/s/42xt2u5zsj98z8m/GLES_Vorwahlquerschnitt_ZA5700_v1-0-0.dta?dl=1. 

On a sidenote this is solved quite conveniently in Stata, where the labels are directly included in the recoding procedure.
``
recode alter (18/23=1 "18bis23") (24/65=2 "24bis65") (66/99=3 ">65"), gen (alterkat)
``
It might be tricky to implement but could work  with regular expressions. For example if we use a special character like `$` or `§`, or ``[ ]`` within the recode string:

````
 rec(efc$e17age, "18:23=1 [18bis23]; 24:65=2 [24bis65]; 66:max=3 [ueber 65]",
+    var.label="Alter kat.",)
````
It might even be able to implement this without breaking the old behavior right? A parameter like ``val.labels="auto"`` could scan for the special character and apply the automated procedure if the special characters are detected.

**Comment by sjPlot** [comment]
There is no variable `q2c` in your example data set.

**Comment by methodds** [comment]
Oh I'm so sorry, I linked the wrong one. Please find the correct version [here](https://www.dropbox.com/s/42xt2u5zsj98z8m/GLES_Vorwahlquerschnitt_ZA5700_v1-0-0.dta?dl=1).

**Comment by sjPlot** [comment]
Please open another issue for your 2nd issue (labelling), so it won't get lost.
