### ISSUE TITLE
`get_var_labels` fail for read_spss(option="haven") imported data when having empty var labels

### ISSUE THREAD

**Issue by eolembrain-leo** [sjPlot/sjmisc#4]
`get_var_labels` seems not to work with [data](https://drive.google.com/open?id=0B8FLxb6Zof5uM0ktNjc5QXRmXzg&authuser=0) having partial empty var labels:

```{r}
raw.data <- sjmisc::read_spss("sample_data.sav")
# str(raw.data)[1:5]
```

![1](https://cloud.githubusercontent.com/assets/8746961/7980691/22feb18c-0adc-11e5-9474-6cbae5bf53af.PNG)

```{r}
sjmisc::get_var_labels(raw.data)
```

![2](https://cloud.githubusercontent.com/assets/8746961/7980695/2984beb6-0adc-11e5-8b5e-9ac3aa196bef.PNG)

But works well with [full-label variables](https://drive.google.com/open?id=0B8FLxb6Zof5uS1J0Tk1IZHRVbVk&authuser=0)

```{r}
raw.data2 <- sjmisc::read_spss("sample_data_full_labels.sav")
# str(raw.data2)[1:5]

sjmisc::get_var_labels(raw.data2)
```

**Comment by sjPlot** [comment]
Which package version are you using (see `packageVersion("sjmisc")`) There was such a bug, which should have been fixed in the current development build (can be installed with `devtools::install_github("sjPlot/sjmisc")`).

**Comment by sjPlot** [comment]
Ah, just saw the sample dataset and tested it. Works with the current development build:

```
get_val_labels(dummy)
$Panel.ID
NULL

$Q1R
[1] "男性" "女性"

$Q2R
[1] "14歲以下" "15~19歲"  "20~24歲"  "25~29歲"  "30~34歲"  "35~39歲"  "40~44歲"  "45歲以上"

$Q3R
[1] "台北市+新北市(新店區/板橋區/三重區/中和區/永和區/新莊區/樹林區)"
[2] "台中市"                                                         
[3] "高雄市"                                                         
[4] "其他地區"                                                       

$Q4C1
NULL

$Q4C2
NULL

$Q4C3
NULL

$Q4C4
NULL

$Q4C5
NULL
```

**Comment by eolembrain-leo** [comment]
Apology for another updating version issue.
Thanks for such efficient package anyway!
