### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by methodds** [sjPlot/sjmisc#40]
Hi,

I'm not sure whether this is a big problem but installing ```sjmisc``` from github raises the following warning at the end: 
````
** preparing package for lazy loading
Error : object ‘zap_inf’ is not exported by 'namespace:sjmisc'
ERROR: lazy loading failed for package ‘sjPlot’
* removing ‘/home/cs/R/x86_64-pc-linux-gnu-library/3.3/sjPlot’
Error: Command failed (1)
````

**Comment by sjPlot** [comment]
You Need to install sjmisc from GitHub first because the new function zap_inf is also used by the current GitHub-Version of sjPlot.
