### ISSUE TITLE
drop_labels()

### ISSUE THREAD

**Issue by methodds** [sjPlot/sjmisc#42]
Hi,

I guess it's a matter of design philosophy as well, but I would like to suggest calling ``drop_labels()```as default for functions like ```sjt.tab()```, and/or let ``set_na()```optionally drop unused labels as well.
Often variables are just copied while encoding missing values like so:

````
d <- read_stata('GLES_Vorwahlquerschnitt_ZA5700_v1-0-0.dta')
vars <- select(d, q41, q119a, q192, q11ba) %>% set_na(-99:-83)
sjt.xtab(vars$q41, vars$q11ba) # gets messed up without drop_labels()
````
It is only a small detail, but I dislike the need to call ``drop_labels()`` in such cases again for dropping any unused NA labels. If one does not use ``drop_labels()``, outputs for ``sjt.xtab()`` etc. get ugly because of the 0 categories for unused labels.

I guess this all comes down to one question for the whole package: Do you ever need unused labels for most analysis again? I personally don't, but maybe this is different for other people.

**Comment by sjPlot** [comment]
I think it is useful to know that if you have defined categories, to see if these have counts or not. Especially if you're not yet familiar with the data, you can see what information is missing, which might be of interest.

Typically, you should call `drop_labels()` directly after loading the data, if you really don't need the labels:

```
d <- read_stata('GLES_Vorwahlquerschnitt_ZA5700_v1-0-0.dta')
vars <- select(d, q41, q119a, q192, q11ba) %>% drop_labels()
sjt.xtab(vars$q41, vars$q11ba)
```

I'm just curious why _haven_ does not tag values as NA - don't these variables have any defined missings in the original Stata file?

**Comment by methodds** [comment]
Nope they don't. They are just regular (most of the time negative) numbers.

**Comment by sjPlot** [comment]
It looks like you're using public data - I bet there's an SPSS-file you could use.

**Comment by pascaltanner** [comment]
As I am also dealing with this kind of question at the moment: I was wondering if one could directly manipulate the labels by using `attributes()`? In my case I would like to keep or drop some of them and change others.

**Comment by sjPlot** [comment]
You can use `set_labels()` with named vectors, or directly `attr(x, "labels") <- ...`.

**Comment by pascaltanner** [comment]
Given this case:

    > get_labels(dt_imp_org[[9]])
    [1] "homme"     "femme"     "pas d'indication"
    > attr(dt_imp_org[[9]], "labels")
        homme    femme    pas d'indication 
            1        2                   7 

How can I remove "pas d'indication" but keep the other labels by using `set_labels()` ?

**Comment by sjPlot** [comment]
You can use `remove_labels()` to remove specific labels, or set only those labels you like with

```
set_labels(dt_imp_org[[9]]) <- c(`homme` = 1, `femme` = 2)
```

Following online-vignette might be interesting for you as well: http://strengejacke.de/sjPlot/sjmisc/

**Comment by sjPlot** [comment]
Btw, @pascaltanner you can also print values in `get_labels()`:

```
get_labels(dt_imp_org[[9]], include.values = "n")
get_labels(dt_imp_org[[9]], include.values = "p")
```

**Comment by pascaltanner** [comment]
Thank you.

**Comment by sjPlot** [comment]
I have posted an "example workflow" in my blog, maybe this is helpful, too:
https://strengejacke.wordpress.com/2016/12/22/exploring-the-european-social-survey-ess-pipe-friendly-workflow-with-sjmisc-part-2-rstats-tidyverse/
