### ISSUE TITLE
Suggestion: Include content of blog posts in a vignette

### ISSUE THREAD

**Issue by methodds** [sjPlot/sjmisc#43]
Hi,

I'd like to suggest combining the most important stuff from the blog posts ([1](https://strengejacke.wordpress.com/2016/09/27/tagged-na-values-and-labelled-data-rstats/), [2](https://strengejacke.wordpress.com/2016/11/14/pipe-friendly-workflow-with-sjplot-sjmisc-and-sjstats-part-1-rstats-tidyverse/), [3](https://strengejacke.wordpress.com/2016/12/22/exploring-the-european-social-survey-ess-pipe-friendly-workflow-with-sjmisc-part-2-rstats-tidyverse/)) in a vignette. This could include basic examples of analysis with labelled data and it would be very useful to have all this captured in one document. Especially for teaching it would be nice, where online access in labs is not always guaranteed and students easily get overwhelmed.

As a more ambitious project you could think about writing an R equivalent to [data analysis with stata](https://www.amazon.com/Data-Analysis-Using-Stata-Third/dp/1597181102/ref=sr_1_3?ie=UTF8&qid=1483960920&sr=8-3&keywords=data+analysis+with+stata) ;-)

**Comment by sjPlot** [comment]
I have some vignettes in rmd-format, but it was too confusing how to include these with knitr in packages... Maybe I find some time figuring this out.

**Comment by sjPlot** [comment]
I guess i would first try to submit a paper to the j stat soft, because this is something i could do at work...

**Comment by sjPlot** [comment]
Not the complete blog-content yet, but more vignettes may follow...

**Comment by methodds** [comment]
nevertheless a very nice start, thank you! :)
