### ISSUE TITLE
to_factor not working as expected?

### ISSUE THREAD

**Issue by aniruhil** [sjPlot/sjmisc#44]
Starting with a clean R session, running RStudio 1.1.39 and R 3.3.2 on OS X Sierra, I was playing with `to_factor()` but the output differs from that expected. What could be going on here? I also reinstalled `sjmisc` via `devtools` so can't be a package version issue.

```
> library(sjmisc)
> data(efc)
> str(efc$e42dep)
```
 atomic [1:908] 3 3 3 4 4 4 4 4 4 4 ...
 - attr(*, "label")= chr "elder's dependency"
 - attr(*, "labels")= Named num [1:4] 1 2 3 4
  ..- attr(*, "names")= chr [1:4] "independent" "slightly dependent" "moderately dependent" "severely dependent"

`> table(to_factor(efc$e42dep))`

  1   2   3   4 
 66 225 306 304 

`> barplot(table(to_factor(efc$e42dep)))`

![plot](https://cloud.githubusercontent.com/assets/1810206/22249370/c2b55642-e210-11e6-92bb-37c48fc087d4.png)

The code below works though with the output in line with the documentation:

```
library(sjPlot)
efc$c172code <- to_factor(efc$c172code)
fit <- lm(barthtot ~ c160age + c12hour + c172code + c161sex, data = efc)
sjt.lm(fit, group.pred = TRUE)

```

**Comment by sjPlot** [comment]
What would you expect as output? :-)

`to_factor()` converts a numeric vector into a factor with numeric levels, but keeps the value and variable labels (which get lost when using `as.factor()`). If you want the value labels set as factor levels, use `to_label()`.

**Comment by aniruhil** [comment]
ah thanks, I messed up with using `to_factor()` instead of `to_label()`. love the package; many thanks!

**Comment by sjPlot** [comment]
There are some tutorials, which might be worth merging into one document:

http://strengejacke.de/sjPlot/sjmisc/

http://strengejacke.de/sjPlot/labelleddata/

https://strengejacke.wordpress.com/2016/12/22/exploring-the-european-social-survey-ess-pipe-friendly-workflow-with-sjmisc-part-2-rstats-tidyverse/
