### ISSUE TITLE
write_spss() coerces data to be contiguous

### ISSUE THREAD

**Issue by michaelwhammer** [sjPlot/sjmisc#46]
When sjmisc::write_spss() writes data to an SPSS file, it coerces data to be contiguous:

```
x <- set_labels(rep(c(1:5, 99), times = 3), c("Strongly Agree" = 1, "Agree" = 2, "Neutral" = 3, "Disagree" = 4, "Strongly Disagree" = 5, "Did Not Answer" = 99))
x
# [1]  1  2  3  4  5 99  1  2  3  4  5 99  1  2  3  4  5 99
#attr(,"labels")
#   Strongly Agree             Agree           Neutral          Disagree Strongly Disagree    Did Not Answer 
#                1                 2                 3                 4                 5                99 
sjmisc::write_spss(data.frame(x), path = "C:/TEMP/temp.sav")
```
And in SPSS the data is now contiguous but is inconsistent with the original structure of the data.
![temp](https://cloud.githubusercontent.com/assets/23129139/22607049/6c9f2304-ea13-11e6-8c99-532fe5644a0e.png)
![temp2](https://cloud.githubusercontent.com/assets/23129139/22607053/7088ed1a-ea13-11e6-9e28-d9cee4d55852.png)

Is is possible to prevent this behavior as it causes a disconnect between the data in SPSS and R?

**Comment by sjPlot** [comment]
As far as I know, categorical or discrete data in SPSS is always "numeric" - or what do you exactly mean?

**Comment by michaelwhammer** [comment]
Correct. The issue isn't that it is coded as "numeric", but that the value 99 gets recoded to be 6 in SPSS, creating a disconnect between how the data appears in R vs how it is outputted into SPSS.

**Comment by sjPlot** [comment]
Ah, I see! Hm, this might be an issue for the *haven* package. If I can reproduce this bug, I'll submit an issue there.

**Comment by sjPlot** [comment]
Does it work when you use `haven::write_spss()`?

**Comment by michaelwhammer** [comment]
I realized I had a typo in my original post. I meant to type `sjmisc::write_spss`, NOT `haven::write_spss`. 

I currently use `haven::write_sav()`, but prior to Haven 1.0 I used `sjmisc::write_spss` and this behavior didn't occur as long as the variables were of class `labelled`. After Haven 1.0 was released I noticed this behavior occurring with `sjmisc::write_spss`.

**Comment by sjPlot** [comment]
Ok, so `sjmisc::write_spss()` does not work properly, but `haven::write_spss()`does?

**Comment by michaelwhammer** [comment]
Correct.

**Comment by sjPlot** [comment]
fixed, will commit this evening.
