### ISSUE TITLE
Error for set_na()

### ISSUE THREAD

**Issue by methodds** [sjPlot/sjmisc#52]
Hi,

I think during the change for the parameter name from *value* to *na* something went wrong. Although the parameter is listed as *na*`in the doc correctly, the following example raises an error:

```
x <- factor(c("a", "b", "c"))
x
set_na(x, na = "b", as.tag = TRUE)

Error in set_na(x, na = "b", as.tag = TRUE) : 
  argument "value" is missing, with no default
```

**Comment by sjPlot** [comment]
Forgot to change this:
https://github.com/sjPlot/sjmisc/blob/master/R/set_na.R#L117

`value` must be replaced by `na` in line 117 - will commit tonight.
