### ISSUE TITLE
Error for write_stata

### ISSUE THREAD

**Issue by methodds** [sjPlot/sjmisc#53]
Hi,

trying to save the example dataset ``efc`` to Stata format does not work for me:

```
library(sjmisc)
data(efc)
write_stata(efc, 'efc.dta')

Writing stata file to 'efc.dta'. Please wait...
Error in eval(substitute(expr), envir, enclos) : 
  not compatible with requested type
```

**Comment by sjPlot** [comment]
This fixes the issue, but I'm not sure if / how it works with labelled data? I have no Stata to test.

**Comment by methodds** [comment]
Writing to Stata works now, but unfortunately all the value labels get lost.

**Comment by methodds** [comment]
And as far as I can tell, value labels now also get lost in SPSS.

**Comment by sjPlot** [comment]
SPSS should not be affected, and last time I tested for SPSS, everything worked fine... Maybe I should try the same approch I use for SPSS also for Stata?

**Comment by methodds** [comment]
Hm that's strange. I just used this syntax

````
library(sjmisc)
data(efc)

frq(efc$e16sex)
write_stata(efc, 'E:\\Dropbox\\lehre\\Methoden der politischen Soziologie\\0 Daten\\efc\\efc.dta')

write_spss(efc, 'E:\\Dropbox\\lehre\\Methoden der politischen Soziologie\\0 Daten\\efc\\efc.sav')
````
And when opening the SPSS files I could not find any value labels. Variable labels are there, similar to Stata. I have SPSS version 21.

**Comment by sjPlot** [comment]
no, you're right. this change breaks SPSS-saving...

**Comment by sjPlot** [comment]
Does `haven::write_dta()` work for you?

**Comment by methodds** [comment]
It does, but there are also no value labels.

**Comment by methodds** [comment]
I have no idea about SPSS, but if you cannot think of any way to directly include value labels for Stata, I could at least come up with a workaround.
 I imagine a small helper function that creates a Stata .do file (= Syntax file), which a user would only need to run once to assign all the value labels. It wouldn't be optimal, but for sure better than no value labels at all.

**Comment by methodds** [comment]
Edit: Just to clarify what I mean, this would basically create the Stata equivalent of this function:

````
write_spsfile <- function(x, path) {

  
  spss_labels <- get_labels(x,
                             include.non.labelled = T,
                             include.values = T)
  
  
  sps.file <- ""
  
  for (var in seq_along(spss_labels)) {
    if (!is.null(spss_labels[[var]])) {
      varname <- names(spss_labels[var])
      values <- names(spss_labels[[var]])
      labs <- spss_labels[[var]]
      labs <- paste0('"', labs, '"')
      
      zipped <- paste(values, labs, collapse = ' ')
      varstring <- paste('VALUE LABELS', varname, zipped, '.\n')
      sps.file <- paste0(sps.file, varstring)
    }
  }
  fileConn<-file(path)
  writeChar(sps.file, path, eos=NULL)
  close(fileConn)
}
````
Which writes value label assignments to an sps file: 
````
VALUE LABELS e15relat 1 "spouse/partner" 2 "child" 3 "sibling" 4 "daughter or son -in-law" 5 "ancle/aunt" 6 "nephew/niece" 7 "cousin" 8 "other, specify" . 
VALUE LABELS e16sex 1 "male" 2 "female" . 
VALUE LABELS e42dep 1 "independent" 2 "slightly dependent" 3 "moderately dependent" 4 "severely dependent" . 
VALUE LABELS c82cop1 1 "never" 2 "sometimes" 3 "often" 4 "always" . 
VALUE LABELS c83cop2 1 "Never" 2 "Sometimes" 3 "Often" 4 "Always" . 
VALUE LABELS c84cop3 1 "Never" 2 "Sometimes" 3 "Often" 4 "Always" . 
VALUE LABELS c85cop4 1 "Never" 2 "Sometimes" 3 "Often" 4 "Always" . 
...
````

**Comment by sjPlot** [comment]
Could you please check how it works for both SPSS and Stata for you?

**Comment by sjPlot** [comment]
I'm not sure when this changed. It did work once for SPSS...

**Comment by methodds** [comment]
Well it has to do something with what you did last night right? Before that, the value labels were not imported properly for me , but at least the ``write_spss`` function did not throw an error.

**Comment by sjPlot** [comment]
importet or exported? I just tested on SPSS 22, and exporting to SPSS works, including value and variable labels. I'll commit the changes tonight, hopefully it works for Stata as well.

**Comment by methodds** [comment]
> importet or exported?

I'm not sure what you mean here, I used ``ẁrite_spss`` (see syntax above). I'll test it again tomorrow and see if it works then.

**Comment by sjPlot** [comment]
You wrote:
>  Before that, the value labels were not imported properly for me

This sounds like the `read_*()`-functions did not work properly, because labels were not imported (=read into R).

**Comment by methodds** [comment]
Hmm no what I meant was "imported into SPSS" =D

**Comment by methodds** [comment]
Just wanted to confirm that it now works for both Stata and SPSS on my end too, thanks for the fix.
