### ISSUE TITLE
a "labelled" package

### ISSUE THREAD

**Issue by larmarange** [sjPlot/sjmisc#7]
Hi

In other projects, I need to deal with labelled variables. Therefore I'm interested by some functions of sjmisc, but only functions related to manipulation of labelled variables.

It could be useful to have a package dealing with and only with manipulation of such variables. This package could later be used by several projects.

Would you be interested by such package?

* if no, would you have any problem that I use some of the codes you wrote for sjmisc?
* If yes, would you want to lead it?

regards

**Comment by sjPlot** [comment]
Do you mean to manipulate labelled class vectors, and keep the labelled class? Or to deal with label attributes in general, also for non-labelled class vectors?

I could contribute to such a package, however, I would not take the lead because I have no clear idea of what the package (functions) should exactly do. You can, of course, also use the code I used in sjmisc (as long as you release it under GPL 3, which is a license requirement from sjmisc).

**Comment by sjPlot** [comment]
Or do you think of "separating" the labelled-class/vector functions from the statistic-functions in sjmisc, to have two packages with a more specific focus?

**Comment by larmarange** [comment]
What I have in mind so far (additional thinking could be required), it's the functions to get the labels (var and val), to modify the labels, and to convert them to factors.

It could also include the definition of the class from `haven` (i.e. `haven` would not be required to create labellised factors).

Some utilities functions like restoring labels after subsetting would also fit within such packages.

Finally, in a second step, once the issue of self-defined missing values will be stabilised in `haven`, it will also include functions to deal with them.

Therefore, it will be based on the  labelled-class/vector functions from `sjmisc` as a start but with the possibility of reorganizing them in a more consistent way and extending them.

For example, my feeling is that functions to convert to a factor would probably need additional testing. In particular, all values don't have to have a label. By default, values with no label should not be converted to `NA`. It should rather be an explicit option decided by the user.

We could also consider that a `to_factor` could accept any kind of vector. In such case, if the vector is already a vector, it will just return the vector. In that way it could be easy to use a generic `table(to_factor(x))` working in all cases. Etc.

I can draft something in the following weeks.

**Comment by sjPlot** [comment]
> For example, my feeling is that functions to convert to a factor would probably need additional testing. In particular, all values don't have to have a label. By default, values with no label should not be converted to NA. It should rather be an explicit option decided by the user.

Do you mean a specific function in sjmisc? Could you provide an example then?

> if the vector is already a vector,

I assume you meant *factor* here? I have fixed that and committed the changes.

**Comment by larmarange** [comment]
> I assume you meant factor here? I have fixed that and committed the changes.

Yes, sorry it's Sunday and it's late

**Comment by larmarange** [comment]
> Do you mean a specific function in sjmisc? Could you provide an example then?

```
> library(haven)
> library(sjmisc)
> x <- labelled(c(1, 2, 3, 2, 4, NA), c(yes = 1, maybe = 2, no = 3))
> x
> x
<Labelled>
[1]  1  2  3  2  4 NA

Labels:
 value label is_na
     1   yes FALSE
     2 maybe FALSE
     3    no FALSE
> as_factor(x)
[1] yes   maybe no    maybe <NA>  <NA> 
Levels: yes maybe no
> to_fac(x)
[1] 1    2    3    2    4    <NA>
Levels: 1 2 3 4
Warning message:
Can't set value labels. Value range of "var" is longer than length of "labels". 
> to_value(x)
[1]  1  2  3  2  4 NA

```

**Comment by larmarange** [comment]
In the previous example, we could have the option to get

```
yes  maybe  no maybe 4 NA
```

**Comment by sjPlot** [comment]
I added some new features, see latest commit and the related examples of the affected functions:

* `get_val_labels` now supports vectors with string label attributes.
* `to_fac` and `to_value` better deal with vectors that don't need to be converted.
* `set_val_labels` and `to_fac` now add additional values as labels, if variable has more valid values than labels that have been supplied as parameter.
* `get_val_labels` gets a `include.non.labelled` parameter to also return non-labelled values as label.
* `to_label` gets a `add.non.labelled` parameter to also convert non-labelled values to labels.
* `set_val_labels` gets a `force.values` parameter to add values without associated labels as labels, too.

**Comment by larmarange** [comment]
Thanks a lot.

In the following weeks I will try to prepare an independent package with all these functions.

Best regards

**Comment by sjPlot** [comment]
I added again some more functions and improved existing ones, including a generic `summary` for labelled-class-objects (which will give you the standard summary for vectors, including a details frequency table).

imho, it is important to keep a _labelled_ package generic, so it would also work with labelled vectors that are not of class `labelled`, or with vector that don't necessarily have _all_ attributes (like `is_na`). Every now and then, I face some problems when using labelled-class-objects with common / base R methods and functions.

**Comment by larmarange** [comment]
Hi.

I have drafted something https://github.com/larmarange/labelled

Please note that this is a work in progress.

Because it would be too complex to maintain compatibility with different
systems of labels, I decided to focus only on the new labelled class.

However, I planned to soon a function foreign_to_labelled to convert a
vector or a data frame from an import with foreign to labelled classes. If
needed other convertors could be written.

The purpose is also to provide all the basic functions to manipulate
labelled data. Most of them are S3 methods.

The idea is that other packages could be able to build their own function
for their respective needs using the basic functions from labelled package.

Of course any feedback is welcome.

Please also note that this just a draft. So changes could be done if
required.

Joseph Larmarange

**Comment by larmarange** [comment]
I didn't developed yet a list of tests for each function but it's planned.
Don't hesitate therefore to provide examples of cases what should be
covered and are not.

Regards

Joseph Larmarange

**Comment by larmarange** [comment]
Hi, 

I have explored your `summary.labelled` function.  Two comments:

- the function assumed you have a labelled numeric vector while you could also have a labelled character vector.
- it creates some issue when performing a `summary` on a data.frame containing variable labels. In fact, you try to provide two different type of information at same time: descriptive statistics and a frequency table. 

The issue is that a labelled vector could corresponds to different type of data. Therefore, I'm thinking not to add a summary method in `labelled` package, bur rather letting other packages to deal with that (for example some functions like `freq` from `questionr` package will be updating to deal with labelled data).

**Comment by larmarange** [comment]
Did you have an opportunity to have a look at the drafted **labelled** package?

Any feedback?

**Comment by sjPlot** [comment]
Yes, I installed a snapshot 2 or 3 days ago - it's very clear and logical to me. And very clean coding, I guess, also due to one of the advantages when focussing on labelled class vectors. :-)

I'll have to try further and give more detailed feedback, if I find any bugs or suggestions...

**Comment by larmarange** [comment]
Ok thanks.
Le 18 juil. 2015 15:12, "Daniel Lüdecke" <notifications@github.com> a
écrit :

**Comment by sjPlot** [comment]
(issue clean-up)
